// permissionMap.js (you can keep this in a utils folder)
export const pageNameToLabelMap = {
  Incoming: "Store Material Inward",
  "Incoming Reprint": "Reprint Label",
  "IQC Check": "IQC Check",
  Requisition: "Material Requisition",
  "Issue Production": "Issue Production",
  "Requisition Receipt": "Requisition Receipt",
  Production: "Production",
  WIP: "WIP",
  "Inventory Reports": "Inventory Reports",
  "Transaction Reports": "Transaction Reports",
  "Production Reports": "Production Reports",
  "Audit Logs": "Activity Logs",
  "Business Partner": "Business Partner",
  "Part Master": "Part Master",
  "BOM Master": "BOM Master",
  "Group Master": "Group Master",
  "Item Master": "Item Master",
  "Warehouse Master": "Warehouse Master",
  "User Management": "User Management",
  "Role Management": "Role Management",
  "System Settings": "System Settings",
};
